# Generated by Django 4.2.11 on 2024-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.CharField(choices=[('CAR', 'car'), ('BIKE', 'bike'), ('AUTO', 'auto')], default='car', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'requested'), ('ACCEPTED', 'accepted'), ('STARTED', 'started'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='STARTED', max_length=30),
        ),
    ]
