# Generated by Django 4.2.11 on 2024-04-19 09:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0004_alter_ride_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
