# Generated by Django 4.2.11 on 2024-04-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0005_alter_ride_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'requested'), ('ACCEPTED', 'accepted'), ('STARTED', 'started'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='REQUESTED', max_length=30),
        ),
    ]
